# Generated by Django 4.2.13 on 2024-06-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Multiform_app", "0002_alter_educationaldetails_mbbspsyr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationaldetails", name="mbbspsyr", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="educationaldetails", name="mdpsyr", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="educationaldetails", name="tenthpsyr", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="educationaldetails",
            name="twelthpsyr",
            field=models.DateField(),
        ),
    ]
