# Generated by Django 4.2.13 on 2024-07-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Multiform_app", "0003_alter_educationaldetails_mbbspsyr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinformation",
            name="status",
            field=models.CharField(
                choices=[
                    ("under_progress", "Under Progress"),
                    ("completed", "Completed"),
                ],
                default="under_progress",
                max_length=20,
            ),
        ),
    ]
