# Generated by Django 4.2.13 on 2024-07-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Multiform_app", "0005_personalinformation_cnfpassword_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Callback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
    ]
