# Generated by Django 4.2.13 on 2024-07-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Multiform_app", "0006_callback"),
    ]

    operations = [
        migrations.RemoveField(model_name="availabilitydetails", name="friend",),
        migrations.RemoveField(model_name="availabilitydetails", name="frist",),
        migrations.RemoveField(model_name="availabilitydetails", name="monend",),
        migrations.RemoveField(model_name="availabilitydetails", name="monst",),
        migrations.RemoveField(model_name="availabilitydetails", name="satend",),
        migrations.RemoveField(model_name="availabilitydetails", name="satst",),
        migrations.RemoveField(model_name="availabilitydetails", name="sunend",),
        migrations.RemoveField(model_name="availabilitydetails", name="sunst",),
        migrations.RemoveField(model_name="availabilitydetails", name="thuend",),
        migrations.RemoveField(model_name="availabilitydetails", name="thust",),
        migrations.RemoveField(model_name="availabilitydetails", name="tueend",),
        migrations.RemoveField(model_name="availabilitydetails", name="tuest",),
        migrations.RemoveField(model_name="availabilitydetails", name="wedend",),
        migrations.RemoveField(model_name="availabilitydetails", name="wedst",),
        migrations.AddField(
            model_name="availabilitydetails",
            name="montime",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="availabilitydetails",
            name="sattime",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="availabilitydetails",
            name="suntime",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="availabilitydetails",
            name="thurstime",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="availabilitydetails",
            name="tuetime",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="availabilitydetails",
            name="wedtime",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
