# Generated by Django 4.2.13 on 2024-07-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Multiform_app", "0007_remove_availabilitydetails_friend_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="availabilitydetails",
            name="fritime",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
