# Generated by Django 4.2.13 on 2024-07-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Multiform_app", "0008_availabilitydetails_fritime"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportingareadetails",
            name="otherText",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
