# Generated by Django 4.2.13 on 2024-07-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Multiform_app", "0009_reportingareadetails_othertext"),
    ]

    operations = [
        migrations.RemoveField(model_name="personalinformation", name="status",),
        migrations.AddField(
            model_name="personalinformation",
            name="stage1status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("under_progress", "Under Progress"),
                    ("verified_by_coordinator", "Verified by Coordinator"),
                    ("verification_failed", "Verification Failed"),
                ],
                default="applied",
                max_length=23,
            ),
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="stage2status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("under_progress", "Under Progress"),
                    ("verified_by_supercoordinator", "Verified by Supercoordinator"),
                    ("verification_failed", "Verification Failed"),
                ],
                default="applied",
                max_length=28,
            ),
        ),
    ]
