# Generated by Django 4.2.13 on 2024-07-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Multiform_app", "0010_remove_personalinformation_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportingareadetails",
            name="ctopt",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="reportingareadetails",
            name="mriopt",
            field=models.CharField(max_length=50),
        ),
    ]
