# Generated by Django 4.2.13 on 2024-07-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Multiform_app", "0011_alter_reportingareadetails_ctopt_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="callback", name="message",),
        migrations.AddField(
            model_name="callback",
            name="ctcheckbox",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="callback",
            name="experience",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="callback",
            name="mammographycheckbox",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="callback",
            name="mricheckbox",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="callback",
            name="qualification",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="callback",
            name="xraycheckbox",
            field=models.BooleanField(default=False),
        ),
    ]
