# Generated by Django 4.2.13 on 2024-07-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Multiform_app", "0014_personalinformation_updatemessage1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personalinformation",
            old_name="updatemessage1",
            new_name="coordinator_message",
        ),
        migrations.RenameField(
            model_name="personalinformation",
            old_name="updatemessage2",
            new_name="supercoordinator_message",
        ),
    ]
