# Generated by Django 4.2.13 on 2024-07-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Multiform_app",
            "0015_rename_updatemessage1_personalinformation_coordinator_message_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="availabilitydetails",
            name="endtime1",
            field=models.CharField(
                blank=True, default="Individual", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="availabilitydetails",
            name="endtime2",
            field=models.CharField(
                blank=True, default="Individual", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="availabilitydetails",
            name="endtime3",
            field=models.CharField(
                blank=True, default="Individual", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="availabilitydetails",
            name="endtime4",
            field=models.CharField(
                blank=True, default="Individual", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="availabilitydetails",
            name="starttime1",
            field=models.CharField(
                blank=True, default="Individual", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="availabilitydetails",
            name="starttime2",
            field=models.CharField(
                blank=True, default="Individual", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="availabilitydetails",
            name="starttime3",
            field=models.CharField(
                blank=True, default="Individual", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="availabilitydetails",
            name="starttime4",
            field=models.CharField(
                blank=True, default="Individual", max_length=100, null=True
            ),
        ),
    ]
