# Generated by Django 4.2.13 on 2024-07-09 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Multiform_app", "0016_alter_availabilitydetails_endtime1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("procedure_name", models.CharField(max_length=100)),
                ("default_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "coordinator_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "radiologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Multiform_app.personalinformation",
                    ),
                ),
            ],
        ),
    ]
