# Generated by Django 4.2.13 on 2024-07-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Multiform_app", "0017_ratelist"),
    ]

    operations = [
        migrations.RemoveField(model_name="ratelist", name="coordinator_rate",),
        migrations.RemoveField(model_name="ratelist", name="default_rate",),
        migrations.RemoveField(model_name="ratelist", name="note",),
        migrations.RemoveField(model_name="ratelist", name="procedure_name",),
        migrations.AddField(
            model_name="ratelist",
            name="ct1",
            field=models.IntegerField(blank=True, default=150, null=True),
        ),
        migrations.AddField(
            model_name="ratelist",
            name="ct2",
            field=models.IntegerField(blank=True, default=150, null=True),
        ),
        migrations.AddField(
            model_name="ratelist",
            name="ct3",
            field=models.IntegerField(blank=True, default=150, null=True),
        ),
        migrations.AddField(
            model_name="ratelist",
            name="ct4",
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
        migrations.AddField(
            model_name="ratelist",
            name="ct5",
            field=models.IntegerField(blank=True, default=225, null=True),
        ),
        migrations.AddField(
            model_name="ratelist",
            name="ct6",
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
        migrations.AddField(
            model_name="ratelist",
            name="ct7",
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
        migrations.AddField(
            model_name="ratelist",
            name="mri1",
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
        migrations.AddField(
            model_name="ratelist",
            name="mri2",
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name="ratelist",
            name="mri3",
            field=models.IntegerField(blank=True, default=250, null=True),
        ),
        migrations.AddField(
            model_name="ratelist",
            name="mri4",
            field=models.IntegerField(blank=True, default=250, null=True),
        ),
        migrations.AddField(
            model_name="ratelist",
            name="mri5",
            field=models.IntegerField(blank=True, default=300, null=True),
        ),
        migrations.AddField(
            model_name="ratelist",
            name="mri6",
            field=models.IntegerField(blank=True, default=300, null=True),
        ),
        migrations.AddField(
            model_name="ratelist",
            name="xray1",
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
        migrations.AddField(
            model_name="ratelist",
            name="xray2",
            field=models.IntegerField(blank=True, default=75, null=True),
        ),
    ]
