# Generated by Django 4.2.13 on 2024-07-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Multiform_app", "0018_remove_ratelist_coordinator_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratelist",
            name="status",
            field=models.CharField(blank=True, default="No Status Yet", max_length=50),
        ),
    ]
